# Copyright (C) 2020, 2023 Mitsubishi Electric Research Laboratories (MERL).
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: MLP
channels:
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - python=3.10
  - scikit-learn-intelex
  - ipykernel
  - pip:
      - gurobi-logtools==3.0.0
      - mock==5.1.0
      - pyomo==6.7.1
      - seaborn==0.13.2
